[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --prefer-offline"]
cacheDirectories = ["node_modules"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]
cacheDirectories = [".next/cache"]

[start]
cmd = "node .next/standalone/server.js"

[variables]
NODE_ENV = "production"
