-- CreateTable
CREATE TABLE IF NOT EXISTS "SupplyAgreement" (
    "id" TEXT NOT NULL,
    "companyName" TEXT NOT NULL,
    "companyAddress" TEXT,
    "companyRegNo" TEXT,
    "contactName" TEXT NOT NULL,
    "contactEmail" TEXT NOT NULL,
    "contactPhone" TEXT,
    "supplyOf" TEXT,
    "siteLocation" TEXT,
    "startDate" TIMESTAMP(3),
    "rates" TEXT,
    "breakdown" TEXT,
    "additionalInfo" TEXT,
    "firstName" TEXT,
    "lastName" TEXT,
    "dateOfBirth" TIMESTAMP(3),
    "niNumber" TEXT,
    "utrNumber" TEXT,
    "address" TEXT,
    "postcode" TEXT,
    "emergencyContactName" TEXT,
    "emergencyContactPhone" TEXT,
    "emergencyContactRelation" TEXT,
    "status" TEXT NOT NULL DEFAULT 'Pending',
    "reviewedBy" TEXT,
    "reviewedAt" TIMESTAMP(3),
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SupplyAgreement_pkey" PRIMARY KEY ("id")
);
